### ISSUE TITLE
Outstanding Prompt Issues

### ISSUE THREAD

**Issue by passy** [yeoman/generator#263]
Now that we landed #250, we should make sure to quickly clear the remaining issues. Those are some I stumbled across:
- [x] Get the grunt-init color style back. (see #199)
- [x] Fix color swapping (1)
- [x] Provide better error messages (2)
- [x] Add support for defaults inferred from the user environment (github username, etc., #199)
- [x] Fix backspace behavior (3)
- [x] No `false` for confirm prompts (https://github.com/SBoudrias/Inquirer.js/issues/15)
### (1) Color Swapping

This might just need adjustments to the generator, but when I run `yo webapp` I first the see the prompt without styling and after hitting enter the line gets replaced with white text (which also happens to be unreadable on a light background).
### (2) Error Messages

An unmodified generator will currently fail without really helpful error messages. In case of `generator-webapp`:

![screenshot from 2013-05-30 12 02 32](https://f.cloud.github.com/assets/9906/584221/12e171e6-c910-11e2-993d-368fd3a152ab.png)

This probably just means throwing more meaningful error messages.
### (3) Backspace behavior

If I'm on a confirmation prompt, enter a character and hit backspace afterwards, the completely line is erased and I see just a prompt like this:

![screenshot from 2013-06-06 21 24 22](https://f.cloud.github.com/assets/9906/620193/ba26237e-cede-11e2-91c3-e17ebf6018dd.png)
